### ISSUE TITLE
Make elevation colors colorblind-friendly

### ISSUE THREAD

**Issue by dash102** [battlecode/battlecode20#189]

**Comment by mnocito** [comment]
maybe add a colorblind option? like a button or smth?

**Comment by dash102** [comment]
Commit 2f3145e has a change to elevation color scheme that's easier for at least the colorblind person I talked to to see - not really a big enough difference for an entirely new option if it ends up just needing this one change, imo

**Comment by arvid220u** [comment]
probably fixed by a9d42a3935e35038ec78c518e94844e4e0aecaa9
