### ISSUE TITLE
consider making unit icons easier to differentiate

### ISSUE THREAD

**Issue by npfoss** [battlecode/battlecode20#208]
right now it's hard to tell the team, and the units themselves are kind of similar too

**Comment by dash102** [comment]
Commit 533d039 has miners that are easier to differentiate now, open to any other suggestions about what's hard to see

**Comment by npfoss** [comment]
that is way better, thanks! I think drones are also kind of hard to tell the team of, but everything else is pretty distinguishable. to be safe, maybe add some more of the team color to fulfillment centers and design schools too please? just like coloring the outline or something would do I think.

**Comment by npfoss** [comment]
bump on this, it was painful during Sprint stream and people have been asking
- [ ] more clearly differentiable drones

**Comment by n8kim1** [comment]
see #346

**Comment by arvid220u** [comment]
seeing as drones are the least visible right now when above water, a possible second solution/part of solution would be to make the color of water lighter

**Comment by arvid220u** [comment]
Closing this for now, as we merged #346
