### ISSUE TITLE
Create bonus ranked scrims upon submission

### ISSUE THREAD

**Issue by j-mao** [battlecode/battlecode20#261]
Help people get their rank faster and not wait for an hour. Might be easier after API endpoint in #253 is done.

**Comment by n8kim1** [comment]
I might be missing something, but what do you mean by "bonus"?

**Comment by j-mao** [comment]
Received a request via discord for new submissions to trigger some scrims so that people can see the effects of their changes immediately on the scoreboard.

Noting here that they can scrim Teh Devs to see bot behaviour, and scoreboard isn't critical to much. Marking as low priority.

**Comment by j-mao** [comment]
Less useful after we moved to elo

**Comment by n8kim1** [comment]
closing bc we've decided to do w/o this
