### ISSUE TITLE
some docstrings missing details

### ISSUE THREAD

**Issue by npfoss** [battlecode/battlecode20#264]
e.g.
- [x] it doesn't mention that canBuildRobot also checks whether there is enough soup available
- [x] the `digDirt` function says you can't dig under robots, but that's only true for buildings

there may be other instances of this, a lot of stuff checks the soup amount

**Comment by arvid220u** [comment]
fixed in 810ab8b1cc3c4cb9052b4916f322e6a7c49e2610
