### ISSUE TITLE
Client shows "incorrect log format", unable to view the game

### ISSUE THREAD

**Issue by arvid220u** [battlecode/battlecode20#275]

**Comment by Diuven** [comment]
Can you attach some example game files for this?

**Comment by j-mao** [comment]
Provided in the discord:
https://2020.battlecode.org/replays/ab6238af3500b8cc44cad9493e9d10.bc20
https://2020.battlecode.org/replays/5bd53c403945a864f77687b0e0f9e6.bc20

**Comment by ingenuir** [comment]
resolved in pr #283
