### ISSUE TITLE
Tournament submissions

### ISSUE THREAD

**Issue by arvid220u** [battlecode/battlecode20#276]
Copy over the last submitted ID to the sprint ID upon successful submission, but stop doing so at exactly 7 pm EST on the submission deadline. Also implement a submissions table for the frontend similar to the Latest Submissions table.

**Comment by j-mao** [comment]
Looks done

**Comment by n8kim1** [comment]
it's ok to keep doing this manually right? or would an auto script for this be a good future idea? (@arvid220u )
