### ISSUE TITLE
Enhance the log css

### ISSUE THREAD

**Issue by Diuven** [battlecode/battlecode20#280]
EFHIII - With just some minor CSS changes, the logs view could be much less painful to look at.

![image](https://user-images.githubusercontent.com/9127047/72228267-995e4b80-35e8-11ea-8e3c-1e503586fea7.png)

**Comment by arvid220u** [comment]
What are the minor CSS changes? Changing the width?

**Comment by Diuven** [comment]
Actually I'm not sure about that either. Probably just changing the width?
I was thinking using different colors and size to enhance readability, but changing width may also help
