### ISSUE TITLE
Add option to hide match results in viewer

### ISSUE THREAD

**Issue by j-mao** [battlecode/battlecode20#288]
For tournament, want to hide spoilers.

This means, instead of "[blah] wins in [blah] rounds on [blah] map", definitely redact the winner, and preferably also:
- redact the number of rounds
- make progress bar not show how far the game has progressed, to keep suspense as to how/when the game will end

**Comment by n8kim1** [comment]
perhaps we should have a "tournament mode" on/off switch in the client? or in the replay file, specify that this match is a tournament match, and do things accordingly

**Comment by n8kim1** [comment]
also a silly "fix" for the rounds/progress would be to pad the end of the game with a bunch of turns (like up to 3K)

**Comment by n8kim1** [comment]
@arvid220u @dash102 @Diuven

**Comment by j-mao** [comment]
We're splitting games infrastructure side. No longer super important

**Comment by arvid220u** [comment]
this is on branch `simpletournament`
