### ISSUE TITLE
Sometimes code compiles locally but not server-side

### ISSUE THREAD

**Issue by n8kim1** [battlecode/battlecode20#299]
something something importing from other packages that exist locally but never make it into the upload????? needs more investigation and digging through discord

@arvid220u @j-mao

**Comment by j-mao** [comment]
People are submitting bots that include other packages that they've written. This can often happen as a result of:
- Writing a bot called `player1` and then importing `player1.HelperClass`
- Starting a "new" bot by running `cp -r player1 player2`
- Forgetting to change the import

This code will still work locally but fail on our servers

**Comment by n8kim1** [comment]
ah yeah this checks out

**Comment by j-mao** [comment]
Closing this as it doesn't seem to be an us problem.
