### ISSUE TITLE
Games somehow end up unqueued

### ISSUE THREAD

**Issue by j-mao** [battlecode/battlecode20#321]
idk what's going on but a small handful of games disappeared from the queue and needed to get requeued manually for the tournament :((

**Comment by j-mao** [comment]
Likely due to HTTP 500 in backend, causing match to be saved in database but not published to queue. Suggest wrapping pub/sub push within try/catch, and retry on failure.

**Comment by n8kim1** [comment]
for reference (and I'm not sure this is actually helpful) they're matches 40807, 40836, 41049
