### ISSUE TITLE
sometimes, scrims are seemingly published to pub/sub but scrim server never logs 

### ISSUE THREAD

**Issue by n8kim1** [battlecode/battlecode20#339]
The messages sent to scrim pub/sub never go acknowledged, leading to matches perpetually queued... Jerry and I suspect that this has to do w the sub behavior, we'll try increasing message length

perhaps the scrim server is overloaded, and then messages expire before it clears?

**Comment by j-mao** [comment]
Related to #321

**Comment by n8kim1** [comment]
@j-mao all our 500 errors are related tbh sigh

**Comment by j-mao** [comment]
Looks maybe fixed now by #328, will monitor for a few more autoscrim rounds

**Comment by j-mao** [comment]
Looks indeed fixed
