### ISSUE TITLE
Performance of pollution code is subpar

### ISSUE THREAD

**Issue by arvid220u** [battlecode/battlecode20#342]
"There's no chance this will be the bottleneck" — well, turns out it is.

Engine should be easy to update, and have the biggest impact (since it happens on a per-turn basis).

To update client this requires a schema change, which might not be worth it (it will turn a 64*64*num_vaporators loop into a 64*64 loop, so it really only matters if we have a lot of vaporators).

**Comment by Diuven** [comment]
Is the performance issue because of updating pollution values themselves or calculating pollutions' effect on robots?

**Comment by arvid220u** [comment]
updating the pollution values

**Comment by arvid220u** [comment]
updating the pollution values
